### ISSUE TITLE
Can't save host

### ISSUE THREAD

**Issue by williamcboehmjr** [JHubi1/ollama-app#1]
When I add my host url it just spins. 
![Screenshot_20240529_020319](https://github.com/JHubi1/ollama-app/assets/112737237/0486ac68-3e91-404d-bfb8-e804b6693289)

**Comment by JHubi1** [comment]
Hi there. Thank you for trying out my app, I really appreciate it.

The infinite loop on startup is my bad, I overlooked that. But I could recreate it and will fix it in the next release.
The issue occurs when trying to add an address as host that doesn't exist. In that case, the code wouldn't know what to do and would freeze in that state. Make sure your Ollama instance is located in the root of your URL; with protocol, subdomains and port. Are you sure you're online and the host you entered is accessible?
