### ISSUE TITLE
Allow advanced server configuration

### ISSUE THREAD

**Issue by devzeebo** [JHubi1/ollama-app#10]
I've set up my Ollama server behind a secure Nginx proxy that checks the Authorization header and does API key verification. I've seen other tutorials online about securing the Ollama API via basic authentication as well. It would be useful to be able to use add an advanced server configuration section to set arbitrary headers when connecting to the server

**Comment by JHubi1** [comment]
Custom headers are already implemented. They'll be released in the next release
