### ISSUE TITLE
App running at 60Hz

### ISSUE THREAD

**Issue by adarsh1001** [JHubi1/ollama-app#11]
Have faced this issue with some other FOSS Flutter apps as well that they don't respect the refresh rate set by the device (in my case, it is forced to 120Hz).

Example issue and fix:
 https://github.com/emavgl/oinkoin/issues/16#issuecomment-1823492267

Device: Nothing Phone (2)
Android: 14

**Comment by JHubi1** [comment]
Are you sure the issue is connected to the app itself? The app is running on a constant 90 fps (on my 90 Hz phone, Google Pixel on Android 14)

**Comment by adarsh1001** [comment]
Yeah currently this is the only app I have that isn't running at 120 for me. For the Oinkoin issue as well, it was running at 120 in Samsung but not Nothing. But one thing I've noticed is that it's always Flutter apps that behave this way.

**Comment by JHubi1** [comment]
Could you try if this build solves the issue?

[ollama.zip](https://github.com/user-attachments/files/15586336/ollama.zip)

**Comment by adarsh1001** [comment]
Working fine with the build at 120Hz now 😄

**Comment by adarsh1001** [comment]
Looking at the package, I guess the issue was because my device has an LTPO panel which varies refresh rate from 1-120Hz?
