### ISSUE TITLE
Cannot connect to android app. CAN connect with laptop

### ISSUE THREAD

**Issue by FDBCF** [JHubi1/ollama-app#13]
Hello,

Found this app on reddit. Looks nice and native. However, I can't connect to my server. It just says invalid host on the app. If I connect using a web browser in my LAN, however, I CAN connect so I imagine I am typing my url in right but doing something else wrong?

Any help with this is appreciated!

**Comment by JHubi1** [comment]
Hi there,

the host you have to enter is the one you can enter in your browser as well. Just try around till a message like "Ollama is running" appears. Then enter the address in the app.

Also make sure your instance is allowed to be accessed. Follow the steps described in #5 to learn more.
