### ISSUE TITLE
Feature Request: Add additional identifiers for models

### ISSUE THREAD

**Issue by jonfairbanks** [JHubi1/ollama-app#14]
First, thanks a ton for developing this app. It has allowed me to completely move off of OpenAI now.

One request I would make is can additional model details be shown in the UI?

For example I have three flavors of Llama 3 downloaded, but it is hard to determine which is which within the app.

Thanks for your consideration!

![Screenshot_20240605_235027.jpg](https://github.com/JHubi1/ollama-app/assets/1957806/47676ba1-0110-44d3-9b93-eea500b8a165)

![Screenshot_20240605_235051_Firefox.jpg](https://github.com/JHubi1/ollama-app/assets/1957806/3074de7d-6b63-4ec2-bf88-80ea2bfab2f8)

**Comment by JHubi1** [comment]
In the latest release (v1.0.3) I added a toggle in settings to do exactly that. After enabling it, the model tags are shown.

Thanks for using my app, I really appreciate it. If you have any other ideas or feature requests, feel free to open a new issue.

**Comment by jonfairbanks** [comment]
Super fast fix, thanks a ton!
