### ISSUE TITLE
Not clearing VRAM after call

### ISSUE THREAD

**Issue by Tycho-S** [JHubi1/ollama-app#16]
Thanks for making this great app!

One thing I noticed, it seems it is requesting the ollama server to immediately clear the model from VRAM again after each request. This means there is a lengthy waiting period for every followup question while the model is loaded back into memory. Could that be configurable? I would set the keep_alive in the api request to -1 so it only gets removed from VRAM when it needs to make space for a different model.

PS I noticed this especially when testing the llava visual model. Which does work great by the way!

**Comment by JHubi1** [comment]
I'll look into it, it shouldn't be too complicated

**Comment by JHubi1** [comment]
Could you try this build: [ollama.zip](https://github.com/user-attachments/files/15749424/ollama.zip) (unpack the zip and install the apk)
It's experimental, expect to run into issues. Does that satisfy your needs?

**Comment by JHubi1** [comment]
Solved it in [v1.1.0](https://github.com/JHubi1/ollama-app/releases/tag/1.1.0).
Feel free to open a new issue if you miss any other features.

**Comment by Tycho-S** [comment]
Thanks for the build! I was at a birthday yesterday night so I couldn't try it. I'll try today and will let you know.

________________________________

**Comment by Tycho-S** [comment]
The ZIP build worked fine, thank you!! It now keeps it in memory making repeat enquiries much faster. I really appreciate it.

**Comment by JHubi1** [comment]
Yes. All three options basically control the same value. The first toggle sets it to `-1` (keep always loaded), the second `0` (don't keep loaded) and the duration selector basically sets the time.
Feel free to open a new issue in case you have other feature requests
