### ISSUE TITLE
Turning off haptics

### ISSUE THREAD

**Issue by Tycho-S** [JHubi1/ollama-app#17]
Sorry another feature request :)

It would be great to be able to turn off the haptics in streaming mode, because my server is pretty fast that so turns into an annoying rumble when I use it. I think it might be more useful with really slow servers.

**Comment by JHubi1** [comment]
I may take this into consideration, but I'd prefer not to implement that, so it has the same behavior as other AI apps

**Comment by Tycho-S** [comment]
But it could be an option 😋

But I understand.. I never tried OpenAI's app because it won't even run if you don't have Google services on your phone. So I didn't know it did that too
________________________________

**Comment by JHubi1** [comment]
I thought about it and came to the conclusion that the option to disable haptics could be practical in some use cases.
I added the option to disable haptic feedback completely in [#db6feba](https://github.com/JHubi1/ollama-app/commit/db6feba1987bf80c39efb6da458a6ad3e859f6bc).
It'll be included in the next release.
