### ISSUE TITLE
How to connect to a host?

### ISSUE THREAD

**Issue by dk-0206** [JHubi1/ollama-app#18]
I am completely new to this as I just read about it on reddit. Can someone help me how to connect it to the host or what are the steps to follow for it to work properly as i don't know what to do.

**Comment by JHubi1** [comment]
I assume you have Ollama running on a PC in your local network.

Firstly, follow the steps discussed in #5 to make Ollama accessible from your phone.

After that, you have to find your PCs local IP. You can do that by either going to your router's device list or getting it in windows CMD (just google "windows get local IP").

Then enter the following in the host field: "http://[ip]:11434"

**Comment by dk-0206** [comment]
Actually, I have ollama app running on my android 14(pixel). Can you help me what ip should i paste in it? Or should i first download models and then enter the ip?![Screenshot_20240616-223841.png](https://github.com/JHubi1/ollama-app/assets/151247305/2185336f-0760-4aad-bc58-1e6dae816956)

**Comment by dk-0206** [comment]
Actually I have ollama running on my android 14 (pixel). Can you help what to write in this host. Should i put my ip in place of localhost or my local ip from router?![Screenshot_20240616-223912.png](https://github.com/JHubi1/ollama-app/assets/151247305/439b41ee-7ac9-4f77-934c-3750c53fd287)

**Comment by JHubi1** [comment]
Have you done something similar to those steps? They seem to work, but I haven't tested it myself 

https://github.com/JHubi1/ollama-app/issues/19#issuecomment-2156793465

**Comment by Sandeep-Devleloper** [comment]
yes that ,invalid host problem,i ve searched allover net to find a solution for it ,but i didn't found anything,please help in this connecting to host

**Comment by JHubi1** [comment]
When you enter the host you used into your browser (on your phone), can you access it?

**Comment by hackmannbr** [comment]
I may be wrong, but I think there are a few problems there...

1. if you try to connect to localhost you are trying to connect to ollama server inside in your phone (doesn't exist). You should use your ollama server ip (computer). Since ollama server runs localhost (127.0.0.1) by default, you will need to change ollama server to listening on all local interfaces (0.0.0.0), so you will connect through your computer ip.  


2. Even if you manage to run ollama locally on your phone, I think there is another problem... If I remember correct, android doesn't accept cleartext connection by default  (...http), you need to do a small change on android code (AndroidManifest.xml) and set to accept it:

android:usesCleartextTraffic="true"


Cheerz

**Comment by JHubi1** [comment]
I can confirm the first one. As already stated above you have to follow #5 to set the host on the server.

The second one shouldn't be an issue, someone in #19 managed to bring it to work without any modifications.

**Comment by makanimike** [comment]
are we allowed to latch onto this issue, or should I create a new one?  
  
I have this issue as well. My ollama is running on my NAS server. I can connect perfectly fine from the same phone using the browser. But in the ollama app it just gives me the "issue: invalid host" error. (and it doesn't even appear to try)

**Comment by JHubi1** [comment]
Nah, writing here is fine.
What text is shown in the browser? The app checks for the content, maybe that's the cause of the issue

**Comment by JHubi1** [comment]
No no, that's exactly what I asked for. But Ollama App (this repo) is a client for [Ollama](https://ollama.com/), not for the UI you're using

**Comment by makanimike** [comment]
I am running a self-hosted instance of ollama. The truenas scale kubernetes implementation which is just (should be) the docker ollama instance. https://github.com/ollama/ollama  
  
Surely, I must be real thick right now, and missing something incredibly basic....

**Comment by JHubi1** [comment]
The host you entered is not an Ollama host, but a frontend. If the host is correct, it should show this exact message:
![Screenshot_20240620-143013~2.png](https://github.com/JHubi1/ollama-app/assets/61345690/da963962-e574-429c-81cc-02232bba6c39)

**Comment by makanimike** [comment]
ok. got it.  
  
simple solution in case anyone else runs into this:  
  
in > Settings > Connections you will find the Ollama Base URL which this app wants. You almost certainly only have to replace the port with 11434.
