### ISSUE TITLE
local openai API compatibility

### ISSUE THREAD

**Issue by shammyfiveducks** [JHubi1/ollama-app#2]
Suggestion: Adding openai API compatibility would be much appreciated. 

E.g 
 localhost:port/v1

/models

Etc

 open it up to connecting to the powerhouses:  llamacpp, localllm and the rest of the local llm openai api supporting software

Cheers

**Comment by JHubi1** [comment]
This might happen in the distant future, but is definitely not a main target. You should take a look into [Ollama](https://ollama.com), it's the most popular local AI system.

**Comment by lp130510** [comment]
Your interface is great, there is no application using the API that looks as good as yours, it would be great if you could support OpenAI's API.

**Comment by arichiardi** [comment]
Not pushing for anything but having OpenAI api compatibility would be very awesome. For instance, it would immediately allow the use of [vllm](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html).
