### ISSUE TITLE
chat breaks for long inputs and at random times

### ISSUE THREAD

**Issue by jmio23** [JHubi1/ollama-app#21]
nice straight forward app :) you could extend compatibility with llama.cpp pretty easily, ollama just wraps llama.cpp, a lot of people use llama.cpp rather than ollama

Currently having a couple of problems, I mostly use 8192 context, and often very long prompts, these fail to send (Nothing like 8192 tokens, but 500-2k) and break the chat 

Chats break after some time, not sure why, keep awake set, but even manually nudging the server doesn't make a difference - I don't have this issue with llama.cpp or ollama wrapper

copy/paste is over complicated
chat content lost when a chat breaks

 I realise this isn't the purpose of this app, its more chat, but it could be more widely useful, couple of suggestions that could massively extend usefulness (eg for programming tasks) beyond chats

Single tap a message to Copy to Clipboard 
Single tap to paste clip board into the input text box

Save full chat (seems like all chat content is lost, if chat breaks?)
Export full chat (a string to the clip board works too)

**Comment by JHubi1** [comment]
I'm aware of the breaking but I have no idea why it happens. The Ollama API just returns an empty response at some point.

You can copy message content by enabling message editing in settings, long pressing at a message and copying the text bot content.

Chats are saved and the save shouldn't be impacted by "the breaking". Just click at the chat in the side bar and it'll get reloaded.

Chat message import and export are already implemented. You can use this as backup or for moving between devices. You find the option in settings under export.

**Comment by jmio23** [comment]
I did try the Save button, but after the chat broke, it vanished from the side bar

**Comment by JHubi1** [comment]
What save button do you mean?

**Comment by JHubi1** [comment]
Hi, I recently discovered a bug in the messaging system. Could you try [v1.1.1](https://github.com/JHubi1/ollama-app/releases/tag/1.1.1) and see if the issue persists?
