### ISSUE TITLE
Speech recognition works in 1.1.1 but not text to speech

### ISSUE THREAD

**Issue by Tycho-S** [JHubi1/ollama-app#22]
Hi! I really love the new voice option in 1.1.1! Thanks for writing it.

The speech recognition works very well, it recognises my prompts quickly. But the responses are not played back. Perhaps it's because you expect google TTS? I have the Samsung one selected on my phone.

Also, I noticed that in voice mode when the response is larger than the screen, I can't scroll down to see the rest. But perhaps that would happen automatically when the speech would get there?

**Comment by JHubi1** [comment]
Hi there, thanks for enjoying my app.

Are you certain that your volume is high enough for TTS to be audible? Could you switch to Google TTS engine and test if the issue persists?

**Comment by Tycho-S** [comment]
Thanks for the quick reply!

Yes the volume is set to max, I do hear the ploing sounds when it start/stops recording voice.

I tried also by setting the google TTS under accessibility settings but that didn't help, it's still not playing it on my phone, sorry.  It's a Samsung S23, Android 14.

**Comment by JHubi1** [comment]
Ok thank you, I'll investigate

**Comment by JHubi1** [comment]
Hi there, it took a while, I'm sorry.
I suspect that there's some issue with my structure. Could you download and install [ollama.zip](https://github.com/user-attachments/files/15889991/ollama.zip)? When installed, say something in Voice Mode to the AI and wait for the answer. Before TTS is triggered, a dialog will pop up. Could you send a screenshot of it (from start to end)?

**Comment by Tycho-S** [comment]
Ok thanks! I'll do it tomorrow, I'm on a business trip and only have my work phone with me on which I can't sideload.

________________________________

**Comment by JHubi1** [comment]
Did you have time to try it yet?

**Comment by Tycho-S** [comment]
Yes sorry I didn't have a chance to do it before i left on holidays. But I got a chance to test it now!

No dialog popped up however. Here's an example attached. I said hello and the response was displayed but not spoken. The version you sent me is still 1.1.1 right?

________________________________

**Comment by Tycho-S** [comment]
![Imagepipe_0](https://github.com/JHubi1/ollama-app/assets/11061880/860e0cdc-0302-41f1-9c19-469392801f42)

**Comment by JHubi1** [comment]
Did you use the API from the ZIP in the message? Are you able to send a second message afterwards by *once* tapping the button? I'll investigate

**Comment by Tycho-S** [comment]
Yes I used the one from the zip of course.


And no the second time it wrote something like "here's a clear and concise summary of "hello",, it didn't state what I actually said
________________________________

**Comment by JHubi1** [comment]
Hi there again,
could you try this build [ollama.zip](https://github.com/user-attachments/files/15976753/ollama.zip)? Is a warning shown in Voice settings? If so, does switching the language to one with a speech symbol next to it solve the issue?

**Comment by Tycho-S** [comment]
Ok thank you! But is it ok if I do this next week? It's a bit difficult now on holidays :(

**Comment by JHubi1** [comment]
Hi there, did you have time to test it yet?

**Comment by JHubi1** [comment]
Had you had time to test the build yet? It should show an icon next to languages that support TTS. Could you test if yours has?

**Comment by JHubi1** [comment]
I know I'm a bit pushy, but I'd really need to know whether the solution makes it clearer for you if the language you selected supports TTS, or if this really is an issue with the app and its implementation of various systems. Please test the build and tell me.
