### ISSUE TITLE
cannot connect to windows host

### ISSUE THREAD

**Issue by Morrigan-Ship** [JHubi1/ollama-app#24]
firewall disabled on windows.
android and windows are in same wifi network.
windows 11
android 13

cmd command:
`ollama run serve`

Host in App:
http://192.168.1.103:11434

error:
`Issue: Invalid Host`

**Comment by JHubi1** [comment]
Could you try following the steps described in #5 ?

**Comment by Morrigan-Ship** [comment]
i fixed via this way:
1. opem CMD as Administrator
2. `setx OLLAMA_HOST 0.0.0.0 /M`
3. `ollama serve`
