### ISSUE TITLE
add stop support

### ISSUE THREAD

**Issue by Morrigan-Ship** [JHubi1/ollama-app#25]
add support stop button when generating text

**Comment by JHubi1** [comment]
Not easily implementable into the current chat system

**Comment by Morrigan-Ship** [comment]
read it
https://github.com/ollama/ollama/issues/2876

**Comment by JHubi1** [comment]
Yes, I know, but still: the way the chat is implemented, it's not easily possible to implement chat cancelation

**Comment by Morrigan-Ship** [comment]
> Yes, I know, but still: the way the chat is implemented, it's not easily possible to implement chat cancelation

https://kush373.medium.com/integrating-ollamas-apis-with-flutter-building-a-conversational-ai-app-local-chatgpt-flutter-42346513d033#:~:text=If%2C%20for%20some%20reason%2C%20the%20chat%20app%20wants%20to%20cancel%20sending%20a%20message%2C%20it%20uses%20abortRequest().%20This%20method%20tells%20the%20ChatDatasource%20to%20stop%20whatever%20it%27s%20doing.

**Comment by JHubi1** [comment]
The way chats are saved, messages are sent, etc hinders me from just stopping the request

**Comment by JHubi1** [comment]
Maybe this will become a feature in the future, but currently an implementation is not possible
