### ISSUE TITLE
bug report Code text block App UI

### ISSUE THREAD

**Issue by Morrigan-Ship** [JHubi1/ollama-app#26]
when AI like Phi3 generating a code block it has cannot word wrap
therefore some of code text is hidden.

**Comment by JHubi1** [comment]
I will investigate the issue, but it could take a while. I'm currently not at my main coding setup. Could you provide a screenshot as an example?

**Comment by Morrigan-Ship** [comment]
![image](https://github.com/JHubi1/ollama-app/assets/138357319/5f124650-148c-4267-a0a1-6769e4ab5305)

**Comment by JHubi1** [comment]
And you're not able to scroll, right? If so I'll look into it

**Comment by Morrigan-Ship** [comment]
> And you're not able to scroll, right?

yes, i cannot

**Comment by JHubi1** [comment]
Hi there, sorry that it took a while. I investigated and found the issue.
As described in [this issue](https://github.com/flutter/flutter/issues/142234), the drawer does not pass scrolls to below widgets. We'll have to wait for a fix for the problem.
In the meantime, I implemented a small fix. Could you try if scrolling works in this build [ollama.zip](https://github.com/user-attachments/files/16099141/ollama.zip) after enabling the fix in interface settings?

**Comment by Morrigan-Ship** [comment]
horizontal scroll still not work
same problem

**Comment by JHubi1** [comment]
Did you enable the fix in settings?

**Comment by Morrigan-Ship** [comment]
oh i enabled fixed thank you

**Comment by Morrigan-Ship** [comment]
but a bad UI when i try to select text from AI response
it show me new pop windows

**Comment by JHubi1** [comment]
If you don't like it you can add a better solution yourself and contribute to the project

**Comment by Morrigan-Ship** [comment]
i have very good idea for selecting ui in chat
a think like last version of Telegram Messenger
in this idea you can select multi message for delete copy or select part of message
and a button top of code block to copy just all codes in block not all textbot message

**Comment by Morrigan-Ship** [comment]
when typing message:
![image](https://github.com/JHubi1/ollama-app/assets/138357319/70fe546d-6e3a-4aef-9abf-66b1c0d96a4e)

when sent message:
![image](https://github.com/JHubi1/ollama-app/assets/138357319/de80966d-1cee-4c05-8413-22dea8f04c17)

**Comment by JHubi1** [comment]
This is a new issue, feel free to open a new one if needed
