### ISSUE TITLE
The behavior system overwrites model definition. 

### ISSUE THREAD

**Issue by nojoyy** [JHubi1/ollama-app#29]
I recently began messing around with model files to make dedicated custom AI chatbots using Ollama. It works great and was entertaining. I then tried to use that same model with the android client, and found that it doesn't work at all.

I imagine you are overwriting the SYSTEM flag via the API call. I'll probably fork and look into it, but the reason I made a Issue is because I then noticed that the Chat Descriptions for previous chats DO act like the character AI... This is a little unexpected for how I understood the API to work.

For demonstration, here is the relevant chat log from my conversations with a custom Snoop Dogg. AI. 

Conversation did not act like expected
![Screenshot_20240630-125800](https://github.com/JHubi1/ollama-app/assets/33733005/5f73c99d-0935-4b21-ae2e-31f005d06990)

But conversation titles are definitely influenced
![Screenshot_20240630-125824](https://github.com/JHubi1/ollama-app/assets/33733005/4a254c18-aa8b-4f87-b29c-261277e73fd3)

**Comment by JHubi1** [comment]
Yes, that's quite easy to explain.
The chat uses the chat message API. Its system message overwrites the one from the model file. Titles use the completion API, and there no system message is set.
I'll look into a fix, shouldn't be too difficult. Maybe I'll add a toggle to disable adding system prompts, so the one from the model file is used.

**Comment by JHubi1** [comment]
Could you try this build? [ollama.zip](https://github.com/user-attachments/files/16087725/ollama.zip)
Does it solve the issue? (you have to disable the usage of system prompt in behavior settings)

**Comment by nojoyy** [comment]
Works great, tysm.

**Comment by nojoyy** [comment]
For anyone having issues, refresh the model in the chat after toggling system behavior. Also make sure the model is actually working on host machine, not all models seem to work with model-files. Obviously if you aren't loading in massive amounts of data into the ai, the system message serves as a solid substitution for playing around.
