### ISSUE TITLE
How to contribute to translation

### ISSUE THREAD

**Issue by Intranox** [JHubi1/ollama-app#31]
I would like to contribute to the translation of the app into Italian, I created a file app_it.arb but I don't know how to insert it

**Comment by JHubi1** [comment]
Hi there, thanks for helping the project.
I like having everything in one spot, so the translations are managed in Crowdin. Please join the project (preferably with the same username as in GitHub) here: https://crowdin.com/project/ollama-app
You can send your file here, in case you have already translated something, I'll put it into the project.

**Comment by Intranox** [comment]
> Hi there, thanks for helping the project. I like having everything in one spot, so the translations are managed in Crowdin. Please join the project (preferably with the same username as in GitHub) here: https://crowdin.com/project/ollama-app You can send your file here, in case you have already translated something, I'll put it into the project.

Thanks, I'm attaching it directly here since I created it and I hope to see it integrated into the app soon.
Ps. I had to create a zip archive as it won't let me upload the file with the .arb extension
[app_it.zip](https://github.com/user-attachments/files/16053744/app_it.zip)

**Comment by JHubi1** [comment]
I added it, thank you. There seem to be some untranslated strings, `settingsHostInvalid` or `settingsMainDeveloper` for example. You might have to take a look into it. If you join, I'd make you a proofreader for Italian, so you can approve strings as well.

**Comment by Intranox** [comment]
> I added it, thank you. There seem to be some untranslated strings, `settingsHostInvalid` or `settingsMainDeveloper` for example. You might have to take a look into it. If you join, I'd make you a proofreader for Italian, so you can approve strings as well.

Thanks, I Joined to the project
