### ISSUE TITLE
I don't know how 5o connect to a host

### ISSUE THREAD

**Issue by Abdullah-Al-Otaibi** [JHubi1/ollama-app#35]
Do I need a computer and connect to it because I don't have one or what do I put in the local host thing btw I'm kinda new on GitHub soo please go easy on me I need a simple explanation if possible thanks ![Screenshot_٢٠٢٤٠٧١٦_١٦٥٩٤٥.jpg](https://github.com/user-attachments/assets/e1fe6f56-b8d4-42c8-8389-0ace76aae36d)

**Comment by JHubi1** [comment]
Yes, you have to have a PC (as described in the readme). Then you have to follow the steps in #5 to be able to connect.

Alternatively you can try installing an Ollama server on your device directly, for that follow the steps in #19, I haven't tested that though
