### ISSUE TITLE
Seriously considering buying a new phone for this

### ISSUE THREAD

**Issue by icasianoian** [JHubi1/ollama-app#37]
Hi, may I know how much RAM is needed, I'm looking at the 24gb ram phone of OnePlus , I'm just wondering if it's gonna be speedy there or not.

**Comment by JHubi1** [comment]
Well, this is just a client, so ram doesn't really matter. I recommend at least 4gb though.

If you want to run models on the device itself, take a look into issue #19

**Comment by icasianoian** [comment]
oh my bad, thought it was local
