### ISSUE TITLE
Add to f-droid - Feature

### ISSUE THREAD

**Issue by PrivacyOsint2** [JHubi1/ollama-app#39]
I understand it is on izzyondroid store. Can this app be added to the f-droid store?

**Comment by JHubi1** [comment]
I'm onto it. I have to collect a few more new features, then I'll make a new release, and then I'll request the addition to the full fdroid repo

**Comment by geekley** [comment]
+1 for adding to f-droid. It's essential for reproducibility and trust. Can you link here the merge request, whenever that is done?

**Comment by Cretezy** [comment]
Hey, any updates on this? @JHubi1
