### ISSUE TITLE
Typo in the system message

### ISSUE THREAD

**Issue by Fr3ddy404** [JHubi1/ollama-app#4]
I think you made a typo in the system message, do you mean to write "like" instead of "lite"?

https://github.com/JHubi1/ollama-app/blob/f9ff88f749efaffa35c01df1fb9eeee1f1a38b40/lib/main.dart#L249-L254

**Comment by JHubi1** [comment]
Yes, this is a typo, thanks for letting me know. I'm currently working on a completely new system for the system message, it won't be an issue there.
