### ISSUE TITLE
Setting up host to local host on same local network just gives a 'Issue: invalidhost'

### ISSUE THREAD

**Issue by mcotdev** [JHubi1/ollama-app#45]
### Requirements

- [X] I have searched the issues of this repository and believe that this is not a duplicate
- [X] I have confirmed this bug exists on the latest version of the app

### Platform

Linux

### Description

Setting up host to local network host.

### Steps to reproduce

Download and install app. Settings > host

### Expected behavior

It accepts the host

### Actual behavior

Invalid host

**Comment by JHubi1** [comment]
Did you follow the steps described in #5 to prepare your host?
