### ISSUE TITLE
Issues connecting

### ISSUE THREAD

**Issue by almostserious** [JHubi1/ollama-app#5]
Might be just my issue, and im missing smth obvious but i simply cannot connect to the host.
Im using the ollama docker and have forwarded the port 0.0.0.0:11434 -> 11434/tcp so it listens on the host. But whatever I do i cannot get the host to connect.
Any pointers on what i am doing wrong? Would love to give this app a try vs the openwebui.

**Comment by JHubi1** [comment]
Hi there. Ollama restricts the hosts that can connect by default. As discussed in [this Ollama issue](https://github.com/ollama/ollama/issues/703), you have to [set the environment variable](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server) `OLLAMA_HOST` to `0.0.0.0` or use something like a tunneling software.

**Comment by almostserious** [comment]
Thanks i saw this but the original fix for docker didnt work for me. Setting the Environmental Variable did work though, thanks.
In case somebody else looking what to add to docker run command: -e OLLAMA HOST="0.0.0.0"

**Comment by JHubi1** [comment]
I'll mark this as close. If you have any other issues, feel free to open another issue. If you have further questions on this one, you can reopen it.
