### ISSUE TITLE
WIN11 HOME

### ISSUE THREAD

**Issue by RobKy1969** [JHubi1/ollama-app#55]
### Requirements

- [X] I have searched the issues of this repository and believe that this is not a duplicate
- [X] I have confirmed this bug exists on the latest version of the app

### Platform

Windows

### Description

"App not compatible with WINDOWS version"

### Steps to reproduce

Go to app file to run installer. Right click, run as admin, it tries to run as ifd WIN8, only older versions of win in drop down. same incompatible message.

### Expected behavior

A clean and easy install.

### Actual behavior

message pops up incompatible with my win version, but i'm running win11 home.

**Comment by JHubi1** [comment]
I'm sorry, I'm not sure what you mean. Could you maybe send a screenshot?

**Comment by RobKy1969** [comment]
Somehow the fifth time i troubleshot it, installer worked.
