### ISSUE TITLE
vision models doesn't seem to work

### ISSUE THREAD

**Issue by yashasnadigsyn** [JHubi1/ollama-app#6]
First of all, Thank you for this app. It works great and the UI is top notch. 
I am using your app for the last 4-5 hours particularly for chat and It works great.
I tried vision model(llava-phi3) now, It doesn't seem to work for me. I tried it 4-5 times again and again. Restarted the app, restarted my PC and nothing seems to work for vision models.

Here's a screenshot:
![image](https://github.com/JHubi1/ollama-app/assets/103478177/c86e14c6-53f6-491c-a602-8f77a0f3c246)

It's stuck there forever. But, llava-phi3 is working on my PC perfectly.
Any Ideas?

**Comment by JHubi1** [comment]
I'm already aware of the issue and had resolved it.
To get a working version, wait for the next version, build from source or try this experimental build:

[ollama.zip](https://github.com/user-attachments/files/15522035/ollama.zip)
