### ISSUE TITLE
Finding Port

### ISSUE THREAD

**Issue by Cibiyanna26** [JHubi1/ollama-app#7]
it's not a issue , but I don't know to how to add the port. Like port do I have to add it would be great if there is a video explanation for this, because I found ollama a opensource to be in our mobile but I kinda feel myself so dumb that I don't know to how to add this port 😅

**Comment by Cibiyanna26** [comment]
If you are planning to make it for web, I am really interested to help you out ... I know there are multiple AI software out there which run by ollama but still you like to have a web version which mapped with your app like I would like to work with you bro 😁

**Comment by JHubi1** [comment]
The default port of Ollama is `11434`. So you most likely have to enter `http://<ip>:11434`. Make sure you have done the steps discussed in #5 to allow Ollama App to connect.

I'm currently looking into providing a desktop version of the app. Web could maybe be added in the future.

**Comment by Cibiyanna26** [comment]
ok bro I will checkout the steps, its still kind of fussy will checkout ...

**Comment by easyexplorar** [comment]
what is the IP address should I enter?  I am using the Android version.  http://<ip>:11434
