### ISSUE TITLE
Chat responses are empty after a certain number of messages

### ISSUE THREAD

**Issue by ejaz4** [JHubi1/ollama-app#9]
Seen on: https://github.com/JHubi1/ollama-app/tree/1.0.1

You can type messages to any model, and responses are provided for up to a certain number of messages (in my case 6/7).
After that, the model responses shown in the chat are empty.

![Screenshot_20240602-203712](https://github.com/JHubi1/ollama-app/assets/73548455/7e3c0178-5448-4c79-bde5-e5ca8af733a1)

Other clients and the CLI are not affected.

**Comment by JHubi1** [comment]
I'll look into it, thanks for creating an issue
